### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by citizenrich** [openhie/openinfoman-fhir#2]
Heyo. I've installed openinfoman and several other stored functions fine. This one errors.

error: Java function org.intrahealth.hapi_transformer:new#0 is unknown

Thoughts? This in inside a docker container.
https://github.com/citizenrich/openinfoman-docker/blob/master/Dockerfile

**Comment by litlfred** [comment]
If I recall correctly, you need the binaries here in the classpath
  https://github.com/openhie/openinfoman-fhir/tree/master/lib

**Comment by citizenrich** [comment]
ahh. well that would make a great deal of sense :) thanks for the guidance!
